# Generated by Django 2.2.6 on 2020-03-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishword',
            options={},
        ),
    ]
